---
- name: Add VLAN to device
  hosts: all
  tasks:
    - name: Add VLAN 10
      arista.eos.eos_vlans:
        config:
          - name: "DMZ"
            vlan_id: 10
            state: active
        state: merged
