---

fabric_name: FABRIC

# Various fabric settings

# Enable vlan aware bundles
evpn_vlan_aware_bundles: false


# Spine Switches
spine:
  defaults:
    platform: cEOS-lab
    bgp_as: 65001
    loopback_ipv4_pool: 192.168.101.0/24
    mlag: false
  nodes:
    - name: spine1
      id: 11
      mgmt_ip: 192.168.0.11/24
    - name: spine2
      id: 12
      mgmt_ip: 192.168.0.12/24
    - name: spine3
      id: 13
      mgmt_ip: 192.168.0.13/24
    - name: spine4
      id: 14
      mgmt_ip: 192.168.0.14/24

# Leaf switches. Most leafs will be l3leaf, not l2leaf.
l3leaf:
  defaults:
    bgp_as: 65100-65199 # Gives a range which will be auto-assigned
    platform: cEOS-lab
    loopback_ipv4_pool: 192.168.101.0/24 # This is loopback0 (underlay)
    vtep_loopback_ipv4_pool: 192.168.102.0/24 # This is loopback1 (VTEP)
    uplink_interfaces: [Ethernet3, Ethernet4, Ethernet5, Ethernet6] # Leaf uplinks
    uplink_switches: [spine1, spine2, spine3, spine4] # Where the leaf uplinks go
    uplink_ipv4_pool: 192.168.103.0/24 # For the p2p interfaces to chopped up into /31s
    mlag_interfaces: [Ethernet1, Ethernet2] # MLAG peer link
    mlag_peer_ipv4_pool: 10.255.252.0/24 # MLAG peer IPs
    mlag_peer_l3_ipv4_pool: 10.255.251.0/24 # iBGP peering between MLAG peers
    virtual_router_mac_address: 00:1c:73:00:00:99 # The vMAC for the anycast gateways
    spanning_tree_mode: mstp # Spanning Tree is still enabled even in EVPN setups
    spanning_tree_priority: 16384 
    mlag: true # By default, use MLAG
  node_groups: 
    - group: mlag1
    # bgp_as is configured automatically from the range, but can be overriden
      nodes:
        - name: leaf1
          id: 1
          mgmt_ip: 192.168.0.21/24
          uplink_switch_interfaces: [Ethernet3, Ethernet3, Ethernet3, Ethernet3]
        - name: leaf2
          id: 2
          mgmt_ip: 192.168.0.22/24
          uplink_switch_interfaces: [Ethernet4, Ethernet4, Ethernet4, Ethernet4]
    - group: mlag2
      bgp_as: 65299 # Overriden automatic allocation for host4/R1 peering
      nodes:
        - name: leaf3
          id: 3
          mgmt_ip: 192.168.0.23/24
          uplink_switch_interfaces: [Ethernet5, Ethernet5, Ethernet5, Ethernet5]
        - name: leaf4
          id: 4
          mgmt_ip: 192.168.0.24/24
          uplink_switch_interfaces: [Ethernet6, Ethernet6, Ethernet6, Ethernet6]



# There's an issue with vEOS with larger MTUs
p2p_uplinks_mtu: 1500

# BFD Settings
bfd_multihop:
  interval: 1200
  min_rx: 1200
  multiplier: 3


# # If you want to put a password on peers
# bgp_peer_groups:
#   # all passwords set to "arista"
#   evpn_overlay_peers:
#     password: Q4fqtbqcZ7oQuKfuWtNGRQ==
#   ipv4_underlay_peers:
#     password: 7x4B4rnJhZB438m9+BrBfQ==
#   mlag_ipv4_underlay_peer:
#     password: 4b21pAdCvWeAqpcKDFMdWw==

# Needed for vEOS/cEOS

bgp_update_wait_install: false
bgp_update_wait_for_convergence: false

# Needed for Arista ATD Lab Environment
dns_domain: atd.lab
mgmt_interface: Management0
mgmt_interface_vrf: MGMT
mgmt_gateway: 192.168.0.1

local_users:
  - name: arista
    privilege: 15
    role: network-admin
# You'll need to do two things
# 1: Log into any leaf or spine and set the password to what the main page says the password is (arista followed by 4 alphanumeric digits)
# 2: Copy the sha512 hash here 
    sha512_password: $6$ucjv9OsdquP7enuu$rOIO3r9CVC74rjrXhlWR9q8Mxr0h5FTcPsk38y2iN39xKUL1WSY9kyZARfc0INajUl7DL6ExKECf0NuzQgbym0
    no_password: yes
# Copy the contents of ~/.ssh/id_rsa.pub, including "ssh-rsa" as this value 
    ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDLkuP6qN7B1faV3ikmF3+WoAUVp22bIUo0hvZA9FLerHsz4zQGDKSIqDeZiDSBQc9DIIdmeBKHkvmBa9Mi5xLtyZ/F8xd4IOxo0bkmPBa9fNx47Us+uf6v3dJXaW0osvdz9S7OTxwd4Qe3VKA5rjF3ZUVqSadGmpT1oTs4Xki/65hiPvk1lMLFJUfFsILKTWbbaz/Pp9bBQzcK/t6dJtBbnJIKZTkclP9emdBkXR9BdPnPX5MInG271gk0abRpLvu3O82Fmn+hbK9iT3v53/4q0JQnhdCYDtr9djjV4kmFGkOeIrSMUO81ep1a0abeiWgPOfX2IhdrgamI0b/INuTP arista@level5v2num1-1-ce0de8f8


cvp_instance_ips:
  - 192.168.0.5
cvp_token_file: /tmp/token
terminattr_disable_aaa: true
terminattr_ingestexclude: "/Sysdb/cell/1/agent,/Sysdb/cell/2/agent"
